[package]
name = "ubc-math-group-project"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Lacewing"]
license = "MIT"
description = "UBC MATH 100 group project template."
repository = "https://github.com/lace-wing/ubc-math-group-project"
keywords = ["University of British Columbia", "UBC", "math", "project"]
categories = ["office", "layout", "components"]
disciplines = ["education", "mathematics"]
exclude = ["tests"]

[template]
path = "template"
entrypoint = "common.typ"
